services:
  - type: web
    name: Royal-Mail
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: KLAVIYO_PRIVATE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Vivital-shipping

databases:
  - name: Vivital-shipping
