services:
  - type: web
    name: vivital-webhooks
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: KLAVIYO_PRIVATE_KEY
        sync: false
databases:
  - name: vivital-shipping
